export const styles = {
  container: {
    flex: 1,
    backgroundColor: '#121015',
    paddingTop: '68px',
    paddingLeft: '30px',
    paddingRight: '30px',
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: 'system-ui, -apple-system, sans-serif',
  },
  title: {
    fontSize: '28px',
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: '40px',
    textAlign: 'center' as const,
    margin: '20px 0',
  },
  circleIcon: {
    width: '120px',
    height: '120px',
    borderRadius: '60px',
    marginBottom: '30px',
    objectFit: 'cover' as const,
    border: '3px solid #333',
  },
  facebookSection: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '20px',
    marginTop: '40px',
  },
  facebookLogo: {
    marginBottom: '10px',
  },
  button: {
    backgroundColor: '#1877F2',
    color: '#FFFFFF',
    border: 'none',
    borderRadius: '8px',
    padding: '12px 24px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    minWidth: '200px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
  },
};